resolver: lts-5.6

packages:
- .
- location:
    git: https://github.com/geraldus/ghcjs-perch.git
    commit: a4bfb7d6a073bcd43f7d04d5dc3876a807f73720
  extra-dep: true
- location:
    git: https://github.com/agocorona/transient.git
    commit: 22b6f80c053100ddb392ab7963697f9169d7d6c7
  extra-dep: true
