resolver: lts-8.3

packages:
- .
- location:
    git: https://github.com/geraldus/ghcjs-perch.git
    commit: 050dbd7c3d9ff5df92b33026127c390e9751d935
  extra-dep: true
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: 72444087d25ac5e88d8eeae6e3613d8aff7beda0
  extra-dep: true
- location:
    git: https://github.com/agocorona/transient-universe.git
    commit: 80c06fff331788b62e6dda5dba161e368c79e2d6

  extra-dep: true
extra-package-dbs: []
flags: {}
