resolver: lts-8.3
packages:
- .
- location:
    git: https://github.com/geraldus/ghcjs-perch.git
    commit: 050dbd7c3d9ff5df92b33026127c390e9751d935
  extra-dep: true
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: d3a96df9ecaf0f09f756fb0fc28901e74c894360
  extra-dep: true
- location:
    git: https://github.com/agocorona/transient-universe.git
    commit: 5133ee2707df3203ccdded97bdbeeacdff1888c5
  extra-dep: true
extra-package-dbs: []
flags: {}
