resolver: lts-7.7
packages:
- .
- location:
    git: https://github.com/geraldus/ghcjs-perch.git
    commit: 1db6e0ae5fa2ec7640991550a0662337263afeef
  extra-dep: true
- '.'
- location:
    git: https://github.com/transient-haskell/transient.git
    commit: 129634b3b32763ab8f50b18516cfabe9706186fc
  extra-dep: true
- location:
    git: https://github.com/transient-haskell/transient-universe.git
    commit: e4bed24e29f526a391c8456ec90fa501784d3303
  extra-dep: true
extra-package-dbs: []
flags: {}
