resolver: lts-6.6
packages:
- .
- location:
    git: https://github.com/geraldus/ghcjs-perch.git
    commit: 1db6e0ae5fa2ec7640991550a0662337263afeef
  extra-dep: true
- '.'
- location:
    git: https://github.com/agocorona/transient.git
    commit: b06645a46462e68a2712de8ecd0d8f325b07a520
  extra-dep: true
- location:
    git: https://github.com/agocorona/transient-universe.git
    commit: 03b4594a39302160493e44311333aa9cfc876b5d
  extra-dep: true
extra-package-dbs: []
flags: {}
